general_configuration: 
    output_directory: "./results_case_one_3c_vanilla" 
    analysis_title: "Clue Points - Case 1" 
    analysis_type: "Regular"
    raw_datasets:
        - "hospital_stay_data.csv"
    curated_datasets:
        - "./results_case_one/hospital_stay_data_curated.csv"

preparation_configuration: 
    data_mining: True
    correlation_matrix: True
    preprocessing_regular:
        enabled: True
        options:
            num_features:
                - "Hospital_code"
                - "City_Code_Hospital"
                - "Available Extra Rooms in Hospital"
                - "Bed Grade"
                - "Visitors with Patient"
                - "Admission_Deposit"
            to_be_dropped: 
                - "patientid"
                - "case_id"
                - "City_Code_Patient"
            ordinal_features: 
                - feature: "Stay"
                  order: ["0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100", "More than 100 Days"]
                  rebin:
                    - group: ["0-10", "11-20"]
                      label: "Short Stay (0-20)"
                    - group: ["21-30","31-40"]
                      label: "Medium Stay (21-40)"
                    - group: ["41-50","51-60", "61-70", "71-80", "81-90", "91-100", "More than 100 Days"]
                      label: "Long Stay (41+)"
                - feature: "Age"
                  order: ["0-10", "11-20", "21-30", "31-40", "41-50" ,"51-60" ,"61-70" ,"71-80" ,"81-90" ,"91-100"]
                - feature: "Severity of Illness"
                  order: ["Minor", "Moderate", "Extreme"]
            other_categorical_features:
                - "Hospital_type_code"
                - "Hospital_region_code"
                - "Department"
                - "Type of Admission"
                - "Ward_Type"
                - "Ward_Facility_Code"
    preprocessing_nlp:
        enabled: False
        options:
            text_features:
            tags_features:
            temporal_features:
            to_be_dropped: 
            oradinal_features: 
            target_feature:
            target_order:

training_configuration:
    train_dataset: "hospital_stay_data_curated.csv"
    val_dataset: ""
    target_feature: "Stay" 
    nepochs: 500 
    optimizer: "Adam"
    learning_rate: 0.0001
    batch_size: 1000 
    buffer_size: 10000
    resampling: True
    verbose: 1 

model_parameters:
    model_name: "my_model" 
    nDlayers: 3 
    vdropout: 0.05 
    nodes_per_layer: 64 
    act_fn: "relu" 
    embedding: False 
    embedding_dim: 32 

validation_configuration:
    compute_shapley: False 
    plot_confusion_matrix: True 
    plot_class_metrics: True
    plot_output_probabilities: True
    plot_log_probability_ratios_and_roc: True
    output_classes:
        - "Short Stay (0-20)"
        - "Medium Stay (21-40)"
        - "Long Stay (41+)"


    
